on: push
name: Rust pre-merge checks

jobs:
  server-checks:
    runs-on: ubuntu-latest
    container: rust:bookworm
    services:
      postgres:
        image: postgres
        env:
         POSTGRES_HOST_AUTH_METHOD: trust
         POSTGRES_DB: clusterizer
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RUSTFLAGS: "-Dwarnings"
      DATABASE_URL: "postgres://postgres@postgres/clusterizer"
      CLUSTERIZER_SECRET: "balls"
      CLUSTERIZER_ADDRESS: "0.0.0.0:3000"
    steps:
      - uses: actions/checkout@v4
      - name: sqlx install
        run: cargo install sqlx-cli
      - name: rustup install clippy
        run: rustup component add clippy rustfmt
      - name: sqlx setup database
        run: sqlx database setup
        working-directory: ./server
      - name: Clippy Check
        run: cargo clippy --all-targets --all-features
      - name: Cargo Format Check
        run: cargo fmt --check